# Site settings
title: Iran University of Science and Technology
course_name: Designing Algorithms
course_description: This course is designed for studying different algorithmes of problem solving such as dynamic programming, greedy, and graph algorithmes. 
course_semester: "Fall 2019"
description: |
Instructor: "Dr.Marzieh Malekimajd"

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/course_algorithm" # the subpath of your site, e.g. /blog/
url: "http://sarina-sh.github.io/course_algorithm" # the base hostname & protocol for your site
syllabus: http://sarina-sh.github.io/course_algorithm/syllabus/
githubdir: 

# Author/user information
email: malekimajd@iust.ac.ir
twitter_username: https://quera.ir/course/3926/
#github_username:  broken_github
authorurl: " "
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false
    course-materials:
        output: true

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
